[build]
  command = "pip install -r requirements.txt && npm install && npm run build"
  publish = "dist"
  functions = "functions"

  [build.environment]
RUST_VERSION = "stable"
PYTHON_VERSION = "3.10"



[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200