[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/functions"
  
[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[cache]
  directory = ".next/cache"
